@echo off
setlocal enabledelayedexpansion

rem Check if pip is installed
pip --version >nul 2>&1
if %errorlevel% neq 0 (
    echo pip is not installed. Installing pip...
    python -m ensurepip --default-pip
    python -m pip install --upgrade pip
)

rem Define variables
set APP_NAME=your_app_name
set SCRIPT_NAME=your_script.py

rem Check if PyInstaller is installed
pyinstaller --version >nul 2>&1
if %errorlevel% neq 0 (
    echo PyInstaller is not installed. Installing...
    pip install pyinstaller
)

rem Run PyInstaller to create the executable
pyinstaller --name %APP_NAME% --onefile %SCRIPT_NAME%

rem Optional: Clean up temporary files generated by PyInstaller
rd /s /q __pycache__ build

echo.
echo %APP_NAME% has been successfully built.
echo.

pause
